// data.js

const menuData = [
  {
    id: "snacks",
    name: "Snacks",
    nameGujarati: "નાસ્તા",
    items: [
      {
        id: "gathiya-jalebi",
        name: "Gathiya - Jalebi - Sambharo - Fry Marcha",
        nameGujarati: "ગાંઠીયા - જલેબી - સંભારો - ફ્રાય મરચા",
      },
      { id: "french-frys", name: "French Frys", nameGujarati: "ફ્રેન્ચ ફ્રાય" },
      { id: "bataka-pauha", name: "Bataka Pauha", nameGujarati: "બટાકા પૌવા" },
      { id: "aloo-paratha", name: "Aloo Paratha", nameGujarati: "આલુ પરાઠા" },
      {
        id: "bread-butter-jam",
        name: "Bread Butter Jam",
        nameGujarati: "બ્રેડ બટર જામ",
      },
      {
        id: "khakhra",
        name: "Khakhra (Plain / Methi / Masala)",
        nameGujarati: "ખાખરા (પ્લેઇન/મેથી/મસાલા)",
      },
      {
        id: "thepla",
        name: "Thepla (Methi / Masala)",
        nameGujarati: "થેપલા (મેથી/મસાલા)",
      },
      { id: "khajali", name: "Khajali", nameGujarati: "ખાજલી" },
      { id: "farci-puri", name: "Farci Puri", nameGujarati: "ફરસી પુરી" },
      {
        id: "khari-variety",
        name: "Khari Variety",
        nameGujarati: "ખારી વેરાયટી",
      },
      {
        id: "biscuit-variety",
        name: "Biscuit Variety",
        nameGujarati: "બીસ્કીટ વેરાયટી",
      },
      {
        id: "masala-bhakhri",
        name: "Masala Bhakhri (Dry)",
        nameGujarati: "મસાલા ભાખરી (ડ્રાય)",
      },
      { id: "upma", name: "Upma", nameGujarati: "ઉપમા" },
      { id: "idli-sambhar", name: "Idli Sambhar", nameGujarati: "ઈડલી સાંભર" },
      {
        id: "medu-vada-sambhar",
        name: "Medu Vada Sambhar",
        nameGujarati: "મેંદુવડા સાંભર",
      },
      {
        id: "baby-dosa",
        name: "Baby Dosa (White Chutney)",
        nameGujarati: "બેબી ઢોસા (વ્હાઇટ ચટણી)",
      },
      {
        id: "veg-pudla",
        name: "Veg. Pudla (Curd / Chutney)",
        nameGujarati: "વેજ. પુડલા (દહીં / ચટણી)",
      },
      { id: "curd", name: "Curd", nameGujarati: "દહીં" },
      { id: "tea-coffee", name: "Tea - Coffee", nameGujarati: "ચા-કોફી" },
    ],
  },
  {
    id: "juices-shakes",
    name: "Juice & Shakes",
    nameGujarati: "જ્યુસ અને શેક્સ",
    items: [
      {
        id: "mocktail-variety",
        name: "Mocktail Variety",
        nameGujarati: "મોકટેલ વેરાયટી",
      },
      { id: "cocktail", name: "Cocktail", nameGujarati: "કોકટેલ" },
      {
        id: "mint-mojito",
        name: "Mint Mojito (Lemon)",
        nameGujarati: "મીન્ટ મોજીતો",
      },
      { id: "paina-orange", name: "Paina Orange", nameGujarati: "પાઇના ઓરેંજ" },
      { id: "musk-melon", name: "Musk Melon", nameGujarati: "ટેટી" },
      { id: "orange", name: "Orange", nameGujarati: "ઓરેંજ" },
      {
        id: "red-green-guava",
        name: "Red / Green Guava",
        nameGujarati: "રેડ / ગ્રીન જામફળ",
      },
      {
        id: "black-green-grapes",
        name: "Black / Green Grapes",
        nameGujarati: "બ્લેક / ગ્રીન દ્રાક્ષ",
      },
      { id: "sweet-lemon", name: "Sweet Lemon", nameGujarati: "સ્વીટ લેમન" },
      { id: "apple", name: "Apple", nameGujarati: "એપલ" },
      {
        id: "kiwi-seasonal",
        name: "Kiwi (Seasonal)",
        nameGujarati: "કીવી (સીઝનલ)",
      },
      {
        id: "watermelon-seasonal",
        name: "Watermelon (Seasonal)",
        nameGujarati: "તરબુચ (સીઝનલ)",
      },
      {
        id: "suger-apple-seasonal",
        name: "Suger Apple (Seasonal)",
        nameGujarati: "સીતાફળ (સીઝનલ)",
      },
      {
        id: "strawberry-seasonal",
        name: "Strawberry (Seasonal)",
        nameGujarati: "સ્ટ્રોબરી (સીઝનલ)",
      },
      { id: "fruit-shake", name: "Fruit Shake", nameGujarati: "ફ્રુટ શેક" },
      { id: "mango-shake", name: "Mango Shake", nameGujarati: "મેંગો શેઇક" },
      {
        id: "sapodilla-shake",
        name: "Sapodilla Shake",
        nameGujarati: "ચીકુ શેઇક",
      },
      {
        id: "faluda",
        name: "Faluda (Rose / Pista / Dry Fruit)",
        nameGujarati: "ફાલુદા (રોઝ/પીસ્તા/ડ્રાય ફ્રુટ)",
      },
    ],
  },
  {
    id: "soups",
    name: "Soups",
    nameGujarati: "સૂપ",
    items: [
      { id: "hot-sour", name: "Hot & Sour", nameGujarati: "હોટ એન્ડ સૌર" },
      { id: "sweet-corn", name: "Sweet Corn", nameGujarati: "સ્વીટ કોર્ન" },
      { id: "veg-manchow", name: "Veg. Manchow", nameGujarati: "વેજ. મન્ચાઉ" },
      {
        id: "cream-of-almond",
        name: "Cream of Almond",
        nameGujarati: "ક્રીમ ઓફ આલ્મન્ડ",
      },
      {
        id: "cream-of-tomato",
        name: "Cream of Tomato",
        nameGujarati: "ક્રિમ ઓફ ટોમેટો",
      },
      {
        id: "tomato-coriander",
        name: "Tomato Coriander",
        nameGujarati: "ટોમેટો કોરીએન્ડર",
      },
      {
        id: "lemon-coriander",
        name: "Lemon Coriander",
        nameGujarati: "લેમન કોરીએન્ડર",
      },
      {
        id: "veg-manchurian",
        name: "Veg. Manchurian",
        nameGujarati: "વેજ. મંચુરીયન",
      },
      { id: "veg-clear", name: "Veg. Clear", nameGujarati: "વેજ. ક્લીયર" },
      {
        id: "corn-vegetable",
        name: "Corn Vegetable",
        nameGujarati: "કોર્ન વેજીટેબલ",
      },
      { id: "clear", name: "Clear", nameGujarati: "ક્લીયર" },
      { id: "minestrone", name: "Minestrone", nameGujarati: "મીનીસ્ટ્રોન" },
      {
        id: "green-garlic-seasonal",
        name: "Green Garlic (Seasonal)",
        nameGujarati: "ગ્રીન ગાર્લીક (સીઝનલ)",
      },
      {
        id: "almond-broccoli",
        name: "Almond Broccoli",
        nameGujarati: "આલ્મન્ડ બ્રોકોલી",
      },
      {
        id: "potato-vegetable",
        name: "Potato Vegetable",
        nameGujarati: "પોટેટો વેજીટેબલ",
      },
      {
        id: "baby-corn-chinese",
        name: "Baby Corn (Chinese)",
        nameGujarati: "બેબી કોર્ન (ચાઇનીઝ)",
      },
      {
        id: "hot-garlic-ginger",
        name: "Hot & Garlic Ginger (Chinese)",
        nameGujarati: "હોટ એન્ડ ગાર્લીક જીંજર (ચાઇનીઝ)",
      },
      {
        id: "cream-of-corn-chinese",
        name: "Cream Of Corn (Chinese)",
        nameGujarati: "ક્રિમ ઓફ કોર્ન (ચાઇનીઝ)",
      },
      {
        id: "tomato-pasta-chinese",
        name: "Tomato Pasta (Chinese)",
        nameGujarati: "ટોમેટો પાસ્તા (ચાઇનીઝ)",
      },
      {
        id: "veg-chawmin-chinese",
        name: "Veg. Chawmin (Chinese)",
        nameGujarati: "વેજ. ચાઉમીન (ચાઇનીઝ)",
      },
      {
        id: "chilli-beans-mexican",
        name: "Chilli Beans (Mexican)",
        nameGujarati: "ચીલી બીન્સ (મેક્સીકન)",
      },
      {
        id: "mexican-corn",
        name: "Mexican Corn",
        nameGujarati: "મેક્સીકન કોર્ન",
      },
      {
        id: "mexican-bengal",
        name: "Mexican Bengal",
        nameGujarati: "મેક્સીકન બેંગાલ",
      },
      { id: "mexican", name: "Mexican", nameGujarati: "મેક્સીકન" },
    ],
  },
  {
    id: "starters",
    name: "Starters",
    nameGujarati: "સ્ટાર્ટર",
    items: [
      {
        id: "veg-dry-manchurian",
        name: "Veg. Dry Manchurian",
        nameGujarati: "વેજ. ડ્રાય મંચુરીયન",
      },
      { id: "kabab-tikki", name: "Kabab Tikki", nameGujarati: "કબાબ ટીક્કી" },
      {
        id: "paneer-chilli-dry",
        name: "Paneer Chilli Dry",
        nameGujarati: "પનીર ચીલી ડ્રાય",
      },
      {
        id: "paneer-chilli-roasted",
        name: "Paneer Chilli Roasted",
        nameGujarati: "પનીર ચીલી રોસ્ટેડ",
      },
      {
        id: "paneer-tikka-roasted",
        name: "Paneer Tikka Roasted",
        nameGujarati: "પનીર ટીક્કા રોસ્ટેડ",
      },
      {
        id: "dragan-potato",
        name: "Dragan Potato (Red Chilli)",
        nameGujarati: "ડ્રેગન પોટાટો (રેડ ચીલી)",
      },
      {
        id: "hara-bhara-kabab",
        name: "Hara Bhara Kabab",
        nameGujarati: "હરાભરા કબાબ",
      },
      {
        id: "italian-volvo",
        name: "Italian Volvo",
        nameGujarati: "ઇટાલીયન વોલ્વો",
      },
      {
        id: "lucknowi-karari-tikki",
        name: "Lucknowi Karari Tikki",
        nameGujarati: "લખનવી કરારી ટીક્કી",
      },
      {
        id: "banarasi-tikki",
        name: "Banarasi Tikki",
        nameGujarati: "બનારસી ટીક્કી",
      },
      {
        id: "cheese-garlic-bread",
        name: "Cheese Garlic Bread",
        nameGujarati: "ચીઝ ગાર્લીક બ્રેડ",
      },
      {
        id: "cheese-gralic-shots",
        name: "Cheese Gralic Shots",
        nameGujarati: "ચીઝ ગાર્લીક શોટ્સ",
      },
      {
        id: "jalapeno-shots",
        name: "Jalapeno Shots",
        nameGujarati: "જેલેપીનો શોટ્સ",
      },
      {
        id: "cracker-pizza",
        name: "Cracker Pizza",
        nameGujarati: "ક્રેકર પીઝા",
      },
      { id: "mini-samosa", name: "Mini Samosa", nameGujarati: "મીની સમોસા" },
      { id: "cheese-boll", name: "Cheese Boll", nameGujarati: "ચીઝ બોલ" },
      {
        id: "italian-tart",
        name: "Italian Tart",
        nameGujarati: "ઇટાલીયન ટાર્ટ",
      },
      {
        id: "italian-shake",
        name: "Italian Shake",
        nameGujarati: "ઇટાલીયન શેક",
      },
      { id: "veg-rock", name: "Veg. Rock", nameGujarati: "વેજ. રોક" },
      { id: "veg-roll", name: "Veg. Roll", nameGujarati: "વેજ. રોલ" },
      { id: "veg-65", name: "Veg. 65", nameGujarati: "વેજ. ૬૫" },
      {
        id: "dry-fruit-choco-cone",
        name: "Dry Fruit Choco Cone",
        nameGujarati: "ડ્રાયફ્રુટ ચોકો કોન",
      },
      {
        id: "dry-fruit-potli",
        name: "Dry Fruit Potli",
        nameGujarati: "ડ્રાયફ્રુટ પોટલી",
      },
    ],
  },
  {
    id: "chat-plate",
    name: "Chat Plate",
    nameGujarati: "ચાટ પ્લેટ",
    items: [
      { id: "rajbhog", name: "Rajbhog (Cold Chat)", nameGujarati: "રાજભોગ" },
      {
        id: "matka-handi",
        name: "Matka Handi (Cold Chat)",
        nameGujarati: "મટકા હાંડી",
      },
      {
        id: "dry-fruit-kachori",
        name: "Dry Fruit Kachori (Cold Chat)",
        nameGujarati: "ડ્રાયફ્રુટ કચોરી",
      },
      {
        id: "aloo-tokri",
        name: "Aloo Tokri (Cold Chat)",
        nameGujarati: "આલુ ટોકરી",
      },
      {
        id: "fruit-tokri",
        name: "Fruit Tokri (Cold Chat)",
        nameGujarati: "ફ્રુટ ટોકરી",
      },
      {
        id: "dahi-bhalla",
        name: "Dahi Bhalla (Cold Chat)",
        nameGujarati: "દહીં ભલ્લા",
      },
      {
        id: "pani-puri",
        name: "Pani Puri (Cold Chat)",
        nameGujarati: "પાણી પુરી",
      },
      {
        id: "chat-basket",
        name: "Chat Basket (Hot Chat)",
        nameGujarati: "ચાટ બાસ્કેટ",
      },
      {
        id: "dry-fruit-hot",
        name: "Dry Fruit (Hot Chat)",
        nameGujarati: "ડ્રાય ફ્રુટ",
      },
      {
        id: "american-hot",
        name: "American (Hot Chat)",
        nameGujarati: "અમેરીકન",
      },
      { id: "golden-hot", name: "Golden (Hot Chat)", nameGujarati: "ગોલ્ડન" },
      { id: "mathura-hot", name: "Mathura (Hot Chat)", nameGujarati: "મથુરા" },
      {
        id: "kashmiri-hot",
        name: "Kashmiri (Hot Chat)",
        nameGujarati: "કાશ્મીરી",
      },
      {
        id: "delhi-papdi",
        name: "Delhi Papdi (Hot Chat)",
        nameGujarati: "દીલ્હી પાપડી",
      },
      {
        id: "amritsari-hot",
        name: "Amritsari (Hot Chat)",
        nameGujarati: "અમ્રીતસરી",
      },
      { id: "rim-zim", name: "Rim Zim (Hot Chat)", nameGujarati: "રીમ ઝીમ" },
      {
        id: "thai-patis",
        name: "Thai Patis (Hot Chat)",
        nameGujarati: "થાઇ પેટીસ",
      },
      {
        id: "thai-curry",
        name: "Thai Curry (Hot Chat)",
        nameGujarati: "થાઇ કરી",
      },
    ],
  },
  {
    id: "sizzler-chinese",
    name: "Sizzler & Chinese",
    nameGujarati: "સિઝલર અને ચાઇનીઝ",
    items: [
      { id: "classic-veg", name: "Classic Veg.", nameGujarati: "ક્લાસીક વેજ." },
      { id: "chinese", name: "Chinese", nameGujarati: "ચાઇનીઝ" },
      { id: "mexican-sizzler", name: "Mexican", nameGujarati: "મેક્સીકન" },
      { id: "italian-sizzler", name: "Italian", nameGujarati: "ઇટાલીયન" },
      { id: "veg-bake", name: "Veg. Bake", nameGujarati: "વેજ. બેક" },
      {
        id: "cheese-pineapple-macaroni",
        name: "Cheese Pineapple Macaroni",
        nameGujarati: "ચીઝ પાઈનેપલ મેકરોની",
      },
      {
        id: "apple-macaroni",
        name: "Apple Macaroni",
        nameGujarati: "એપલ મેકરોની",
      },
      {
        id: "almond-macaroni",
        name: "Almond Macaroni",
        nameGujarati: "આલ્મન્ડ મેકરોની",
      },
      {
        id: "mongolian-pasta",
        name: "Mongolian Pasta",
        nameGujarati: "મેંગોલીયન પાસ્તા",
      },
      {
        id: "cheese-macaroni",
        name: "Cheese Macaroni",
        nameGujarati: "ચીઝ મેકરોની",
      },
      { id: "chinese-bhel", name: "Chinese Bhel", nameGujarati: "ચાઇનીઝ ભેળ" },
      {
        id: "veg-hakka-noodles",
        name: "Veg. Hakka Noodles",
        nameGujarati: "વેજ. હક્કા નુડલ્સ",
      },
      {
        id: "veg-manchurian-dry-gravy",
        name: "Veg. Manchurian Dry / Gravy",
        nameGujarati: "વેજ. મંચુરીયન ડ્રાય / ગ્રેવી",
      },
      { id: "veg-crispy", name: "Veg. Crispy", nameGujarati: "વેજ. ક્રિસ્પી" },
      {
        id: "chinese-samosa",
        name: "Chinese Samosa",
        nameGujarati: "ચાઇનીઝ સમોસા",
      },
      { id: "spring-roll", name: "Spring Roll", nameGujarati: "સ્પ્રીંગ રોલ" },
      {
        id: "american-chopsuey",
        name: "American Chopsuey",
        nameGujarati: "અમેરીકન ચોપ્સી",
      },
      {
        id: "schezwan-noodles",
        name: "Schezwan Noodles",
        nameGujarati: "સેઝવાન નુડલ્સ",
      },
      { id: "chinese-tawa", name: "Chinese Tawa", nameGujarati: "ચાઇનીઝ તવા" },
    ],
  },
  {
    id: "italian-south-indian",
    name: "Italian & South Indian",
    nameGujarati: "ઇટાલિયન અને સાઉથ ઇન્ડિયન",
    items: [
      {
        id: "italian-pizza",
        name: "Italian Pizza",
        nameGujarati: "ઇટાલીયન પીઝા",
      },
      { id: "cheese-pizza", name: "Cheese Pizza", nameGujarati: "ચીઝ પીઝા" },
      { id: "onian-pizza", name: "Onian Pizza", nameGujarati: "ઓનીયન પીઝા" },
      {
        id: "margarita-pizza",
        name: "Margarita Pizza",
        nameGujarati: "માર્ગેરીટા પીઝા",
      },
      {
        id: "pasta-red-white",
        name: "Pasta (Red / White)",
        nameGujarati: "પાસ્તા (રેડ / વ્હાઇટ)",
      },
      {
        id: "pasta-macaroni-penne",
        name: "Pasta (Macaroni / Penne)",
        nameGujarati: "પાસ્તા (મેક્રોની / પેની)",
      },
      { id: "palak-pasta", name: "Palak Pasta", nameGujarati: "પાલક પાસ્તા" },
      { id: "bake-pasta", name: "Bake Pasta", nameGujarati: "બેક પાસ્તા" },
      {
        id: "potato-roasted",
        name: "Potato Roasted",
        nameGujarati: "પોટેટો રોસ્ટેડ",
      },
      {
        id: "rassian-cheese-tost",
        name: "Rassian Cheese Tost",
        nameGujarati: "રશીયન ચીઝ ટોસ્ટ",
      },
      {
        id: "dosa",
        name: "Dosa (Sada / Masala / Maysuri)",
        nameGujarati: "ઢોસા (સાદા / મસાલા / મૈસુરી)",
      },
      {
        id: "rava-dosa",
        name: "Rava Dosa (Sada / Masala / Maysuri)",
        nameGujarati: "રવા ઢોસા (સાદા / મસાલા / મૈસુરી)",
      },
      { id: "spring-dosa", name: "Spring Dosa", nameGujarati: "સ્પ્રીંગ ઢોસા" },
      {
        id: "idli-sambhar-south",
        name: "Idli Sambhar",
        nameGujarati: "ઇડલી સાંભર",
      },
      {
        id: "idli-taka-tak",
        name: "Idli Taka Tak",
        nameGujarati: "ઇડલી ટકાટક",
      },
      {
        id: "schezwan-idli",
        name: "Schezwan Idli",
        nameGujarati: "સેઝવાન ઇડલી",
      },
      { id: "idli-fry", name: "Idli Fry", nameGujarati: "ઇડલી ફ્રાય" },
      { id: "medu-vada-south", name: "Medu Vada", nameGujarati: "મેંદુવડા" },
      {
        id: "uttapam",
        name: "Uttapam (Sada / Masala / Onion / Mix / Cheese)",
        nameGujarati: "ઉત્તપમ (સાદા / મસાલા / ઓનીયન / મીક્સ / ચીઝ)",
      },
      { id: "paneer-chilla", name: "Paneer Chilla", nameGujarati: "પનીર ચીલા" },
    ],
  },
  {
    id: "salads-sweets",
    name: "Salads & Sweets",
    nameGujarati: "સલાડ અને મીઠાઈ",
    items: [
      { id: "fresh-tomato", name: "Fresh Tomato", nameGujarati: "ફ્રેશ ટમેટા" },
      { id: "fresh-carrot", name: "Fresh Carrot", nameGujarati: "ફ્રેશ ગાજર" },
      {
        id: "fresh-cucumber",
        name: "Fresh Cucumber",
        nameGujarati: "ફ્રેશ કાકડી",
      },
      {
        id: "fresh-cabbage",
        name: "Fresh Cabbage",
        nameGujarati: "ફ્રેશ કોબીજ",
      },
      { id: "mix-salad", name: "Mix Salad", nameGujarati: "મીક્સ સલાડ" },
      { id: "achar", name: "Achar", nameGujarati: "આચાર" },
      { id: "kachri", name: "Kachri", nameGujarati: "કાચરી" },
      { id: "namkeen", name: "Namkeen", nameGujarati: "નમકીન" },
      { id: "fryums", name: "Fryums", nameGujarati: "ફ્રાયમ્સ" },
      {
        id: "raita",
        name: "Raita (Boondi / Pineappe / Mix Fruit / Veg)",
        nameGujarati: "રાયતા (બુંદી / પાઈનેપલ / મીક્સ ફ્રુટ / વેજ.)",
      },
      {
        id: "shyam-dairy-rajkot",
        name: "Shyam Dairy - Rajkot (Liquid)",
        nameGujarati: "શ્યામ ડેરી ફાર્મ - રાજકોટ",
      },
      {
        id: "shiv-shakti-dairy-farm-rajkot",
        name: "Shiv Shakti Dairy Farm - Rajkot (Liquid)",
        nameGujarati: "શિવશક્તિ ડેરી ફાર્મ - રાજકોટ",
      },
      {
        id: "creaminess-junagadh",
        name: "Creaminess - Junagadh (Liquid)",
        nameGujarati: "ક્રિમીનેશ - જૂનાગઢ",
      },
      {
        id: "kamal-bhog",
        name: "Kamal Bhog (Bengali)",
        nameGujarati: "કમલ ભોગ",
      },
      { id: "hiramani", name: "Hiramani (Bengali)", nameGujarati: "હીરામણી" },
      {
        id: "makhan-santra",
        name: "Makhan Santra (Bengali)",
        nameGujarati: "મખનસંતરા",
      },
    ],
  },
  {
    id: "sweets-mithai",
    name: "Sweets (Mithai)",
    nameGujarati: "મીઠાઈ",
    items: [
      {
        id: "hot-kaju-mesub",
        name: "Hot Kaju Mesub",
        nameGujarati: "કાજુ મેસુબ",
      },
      {
        id: "rajbhog-mesub",
        name: "Rajbhog Mesub",
        nameGujarati: "રાજભોગ મેસુબ",
      },
      {
        id: "mohan-thal-lachko",
        name: "Mohan Thal Lachko",
        nameGujarati: "મોહન થાળ લચકો",
      },
      {
        id: "adadiya-lachko-seasonal",
        name: "Adadiya Lachko (Seasonal)",
        nameGujarati: "અડદીયા લચકો (સીઝનલ)",
      },
      {
        id: "dry-fruit-halwa",
        name: "Dry Fruit Halwa",
        nameGujarati: "ડ્રાયફ્રુટ હલવો",
      },
      {
        id: "kesar-dry-fruit",
        name: "Kesar Dry Fruit",
        nameGujarati: "કેસર ડ્રાયફ્રુટ",
      },
      { id: "kesar-almond", name: "Kesar Almond", nameGujarati: "કેસર બદામ" },
      { id: "anjeer-halwa", name: "Anjeer Halwa", nameGujarati: "અંજીર હલવો" },
      {
        id: "anjeer-akhrot-halwa",
        name: "Anjeer Akhrot Halwa",
        nameGujarati: "અંજીર અખરોટ હલવો",
      },
      {
        id: "gulab-gulkand-halwa",
        name: "Gulab Gulkand Halwa",
        nameGujarati: "ગુલાબ ગુલકંદ હલવો",
      },
      {
        id: "badam-butter-scotch",
        name: "Badam Butter Scotch",
        nameGujarati: "બદામ બટરસ્કોચ",
      },
      { id: "afghan-halwa", name: "Afghan Halwa", nameGujarati: "અફઘાન હલવો" },
      {
        id: "coconut-halwa",
        name: "Coconut Halwa",
        nameGujarati: "કોકોનટ હલવો",
      },
      { id: "dry-churmu", name: "Dry Churmu", nameGujarati: "ડ્રાય ચુરમુ" },
      {
        id: "dry-fruti-boondi",
        name: "Dry Fruti Boondi",
        nameGujarati: "ડ્રાયફ્રુટ બુંદી",
      },
      {
        id: "excotica-dairy",
        name: "Excotica (White / Chocolate / Rose)",
        nameGujarati: "એક્સોટીકા (વ્હાઇટ / ચોકલેટ / રોઝ)",
      },
      { id: "kaju-katli", name: "Kaju Katli", nameGujarati: "કાજુ કતરી" },
      { id: "bridge-ladoo", name: "Bridge Ladoo", nameGujarati: "બ્રિજ લાડુ" },
      { id: "paneer-ladoo", name: "Paneer Ladoo", nameGujarati: "પનીર લાડુ" },
      { id: "anjeer-pak", name: "Anjeer Pak", nameGujarati: "અંજીર પાક" },
      { id: "ras-malai", name: "Ras Malai", nameGujarati: "રસ મલાઈ" },
    ],
  },
  {
    id: "punjabi-dishes",
    name: "Punjabi Dishes",
    nameGujarati: "પંજાબી",
    items: [
      {
        id: "sp-patel-paneer",
        name: "Sp. Patel Paneer",
        nameGujarati: "સ્પે. પટેલ પનીર",
      },
      {
        id: "paneer-pasanda",
        name: "Paneer Pasanda",
        nameGujarati: "પનીર પસંદા",
      },
      {
        id: "paneer-lababdar",
        name: "Paneer Lababdar",
        nameGujarati: "પનીર લવાબદાર",
      },
      {
        id: "paneer-toofani",
        name: "Paneer Toofani",
        nameGujarati: "પનીર તુફાની",
      },
      {
        id: "paneer-angara",
        name: "Paneer Angara",
        nameGujarati: "પનીર અંગારા",
      },
      {
        id: "paneer-patiyala",
        name: "Paneer Patiyala",
        nameGujarati: "પનીર પટીયાલા",
      },
      {
        id: "paneer-chatpata",
        name: "Paneer Chatpata",
        nameGujarati: "પનીર ચટપટા",
      },
      {
        id: "paneer-taka-tak",
        name: "Paneer Taka Tak",
        nameGujarati: "પનીર ટકાટક",
      },
      {
        id: "paneer-butter-masala",
        name: "Paneer Butter Masala",
        nameGujarati: "પનીર બટર મસાલા",
      },
      {
        id: "paneer-tikka-masala",
        name: "Paneer Tikka Masala",
        nameGujarati: "પનીર ટીક્કા મસાલા",
      },
      { id: "sahi-paneer", name: "Sahi Paneer", nameGujarati: "શાહી પનીર" },
      {
        id: "paneer-bhurji",
        name: "Paneer Bhurji (White / Red Gravy)",
        nameGujarati: "પનીર ભુરજી (વ્હાઇટ / રેડ ગ્રેવી)",
      },
      { id: "palak-paneer", name: "Palak Paneer", nameGujarati: "પાલક પનીર" },
      {
        id: "palak-corn-paneer",
        name: "Palak Corn Paneer",
        nameGujarati: "પાલક કોર્ન પનીર",
      },
      {
        id: "paneer-baby-corn",
        name: "Paneer Baby Corn",
        nameGujarati: "પનીર બેબી કોર્ન",
      },
      {
        id: "paneer-corn-capsicum",
        name: "Paneer Corn Capsicum",
        nameGujarati: "પનીર કોર્ન કેપ્સીકમ",
      },
      {
        id: "baby-corn-mutter-paneer",
        name: "Baby Corn Mutter Paneer",
        nameGujarati: "બેબી કોર્ન મટર પનીર",
      },
      {
        id: "mathi-mutter-malai",
        name: "Mathi Mutter Malai (White Gray)",
        nameGujarati: "મેથી મટર મલાઇ (વ્હાઇટ ગ્રેવી)",
      },
      {
        id: "paneer-hydrabadi",
        name: "Paneer Hydrabadi",
        nameGujarati: "પનીર હૈદ્રાબાદી",
      },
    ],
  },
  {
    id: "gujarati-subzi",
    name: "Gujarati Subzi",
    nameGujarati: "ગુજરાતી સબ્જી",
    items: [
      {
        id: "sp-patel-vegetable",
        name: "Sp. Patel Vegetable",
        nameGujarati: "સ્પે. પટેલ વેજ.",
      },
      { id: "veg-mix", name: "Veg. Mix", nameGujarati: "મીક્સ વેજ." },
      { id: "veg-toofani", name: "Veg. Toofani", nameGujarati: "વેજ. તુફાની" },
      { id: "veg-handi", name: "Veg. Handi", nameGujarati: "વેજ. હાંડી" },
      { id: "veg-jaipuri", name: "Veg. Jaipuri", nameGujarati: "વેજ. જયપુરી" },
      {
        id: "veg-kolhapuri",
        name: "Veg. Kolhapuri",
        nameGujarati: "વેજ. કોલ્હાપુરી",
      },
      { id: "veg-kadai", name: "Veg. Kadai", nameGujarati: "વેજ. કડાઈ" },
      {
        id: "veg-mutter-maharani",
        name: "Veg. Mutter Maharani (Green / Golden Gravy)",
        nameGujarati: "વેજ. મટર મહારાની (ગ્રીન / ગોલ્ડન ગ્રેવી)",
      },
      {
        id: "veg-corn-dumaloo",
        name: "Veg. Corn Dumaloo",
        nameGujarati: "વેજ. કોર્ન દમાલુ",
      },
      { id: "dumaloo", name: "Dumaloo", nameGujarati: "દમાલુ" },
      {
        id: "punjabi-chole",
        name: "Punjabi Chole",
        nameGujarati: "પંજાબી છોલે",
      },
      {
        id: "corn-capsicum-potato",
        name: "Corn Capsicum Potato",
        nameGujarati: "કોર્ન કેપ્સીકમ પોટાટો",
      },
      {
        id: "rajawadi-undhiyu",
        name: "Rajawadi Undhiyu",
        nameGujarati: "રજવાડી ઉધીયુ",
      },
      {
        id: "surti-green-undhiyu",
        name: "Surti Green Undhiyu",
        nameGujarati: "સુરતી ગ્રીન ઉધીયુ",
      },
      {
        id: "patra-turiya-vatana",
        name: "Patra Turiya Vatana",
        nameGujarati: "પાત્રા તુરીયા વટાણા",
      },
      {
        id: "bharela-ringan-bataka-marcha",
        name: "Bharela Ringan Bataka Marcha",
        nameGujarati: "ભરેલા રીંગણ બટાકા મરચા",
      },
      { id: "kaju-karela", name: "Kaju Karela", nameGujarati: "કાજુ કારેલા" },
      {
        id: "masala-bhindi",
        name: "Masala Bhindi",
        nameGujarati: "મસાલા ભીંડી",
      },
      {
        id: "masala-bhindi-capsicum-aloo-chips",
        name: "Masala Bhindi Capsicum Aloo Chips",
        nameGujarati: "મસાલા ભીંડી કેપ્સીકમ આલુ ચીપ્સ",
      },
      { id: "guvar-dhokli", name: "Guvar Dhokli", nameGujarati: "ગુવાર ઢોકળી" },
      {
        id: "flower-vatana",
        name: "Flower Vatana",
        nameGujarati: "ફ્લાવર વટાણા",
      },
      { id: "suki-bhaji", name: "Suki Bhaji", nameGujarati: "સુકીભાજી" },
      { id: "aloo-mutter", name: "Aloo Mutter", nameGujarati: "આલુ મટર" },
    ],
  },
  {
    id: "kathiyawadi-kathol",
    name: "Kathiyawadi Kathol",
    nameGujarati: "કાઠિયાવાડી કઠોળ",
    items: [
      { id: "sev-tomata", name: "Sev Tomata", nameGujarati: "સેવ ટમેટા" },
      {
        id: "lasaniya-bataka",
        name: "Lasaniya Bataka",
        nameGujarati: "લસણીયા બટાકા",
      },
      {
        id: "kaju-gathiya",
        name: "Kaju Gathiya",
        nameGujarati: "કાજુ ગાંઠીયા",
      },
      {
        id: "lasaniya-gathiya",
        name: "Lasaniya Gathiya",
        nameGujarati: "લસણીયા ગાંઠીયા",
      },
      {
        id: "rajwadi-dhokli",
        name: "Rajwadi Dhokli",
        nameGujarati: "રજવાડી ઢોકળી",
      },
      {
        id: "ringan-bharthu",
        name: "Ringan Bharthu",
        nameGujarati: "રીંગણ ભરથુ",
      },
      { id: "sev-dungri", name: "Sev Dungri", nameGujarati: "સેવ ડુંગળી" },
      { id: "dahi-thikari", name: "Dahi Thikari", nameGujarati: "દહીં તીખારી" },
      { id: "moong-masala", name: "Moong Masala", nameGujarati: "મગ મસાલા" },
      { id: "chole-chana", name: "Chole Chana", nameGujarati: "છોલે ચણા" },
      { id: "choli", name: "Choli", nameGujarati: "ચોળી" },
      { id: "dasi-chana", name: "Dasi Chana", nameGujarati: "દેશી ચણા" },
      {
        id: "moong-chhali-dal",
        name: "Moong Chhali Dal",
        nameGujarati: "મગ છડી દાળ",
      },
      { id: "adad-dal", name: "Adad Dal", nameGujarati: "અડદ દાળ" },
    ],
  },
  {
    id: "indian-breads",
    name: "Indian Breads",
    nameGujarati: "ઇન્ડિયન બ્રેડ્સ",
    items: [
      { id: "butter-roti", name: "Butter Roti", nameGujarati: "બટર રોટી" },
      {
        id: "baby-butter-naan",
        name: "Baby Butter Naan",
        nameGujarati: "બેબી બટર નાન",
      },
      {
        id: "butter-paratha",
        name: "Butter Paratha",
        nameGujarati: "બટર પરાઠા",
      },
      {
        id: "laccha-paratha",
        name: "Laccha Paratha",
        nameGujarati: "લચ્છા પરાઠા",
      },
      { id: "stuff-naan", name: "Stuff Naan", nameGujarati: "સ્ટફ નાન" },
      { id: "pudina-naan", name: "Pudina Naan", nameGujarati: "ફુદીના નાન" },
      { id: "methi-naan", name: "Methi Naan", nameGujarati: "મેથી નાન" },
      {
        id: "amritsari-naan",
        name: "Amritsari Naan",
        nameGujarati: "અમૃતસરી નાન",
      },
      { id: "palak-naan", name: "Palak Naan", nameGujarati: "પાલક નાન" },
      { id: "garlic-naan", name: "Garlic Naan", nameGujarati: "ગાર્લીક નાન" },
      {
        id: "butter-kulcha",
        name: "Butter Kulcha (Stuff / Pudina)",
        nameGujarati: "બટર કુલ્ચા (સ્ટફ / ફુદીના)",
      },
      {
        id: "fulka-roti-live",
        name: "Fulka Roti (Live)",
        nameGujarati: "ફુલ્કા રોટલી (લાઇવ)",
      },
      {
        id: "tawa-paratha-roasted-fry",
        name: "Tawa Paratha (Roasted / Fry)",
        nameGujarati: "તવા પરાઠા (રોસ્ટેડ / ફ્રાય)",
      },
      {
        id: "masala-thepla",
        name: "Masala Thepla",
        nameGujarati: "મસાલા થેપલા",
      },
      { id: "tawa-bhakri", name: "Tawa Bhakri", nameGujarati: "તવા ભાખરી" },
      { id: "puri", name: "Puri", nameGujarati: "પુરી" },
      { id: "masala-puri", name: "Masala Puri", nameGujarati: "મસાલા પુરી" },
      {
        id: "aloo-paratha-bread",
        name: "Aloo Paratha",
        nameGujarati: "આલુ પરાઠા",
      },
      {
        id: "biscuit-paratha",
        name: "Biscuit Paratha",
        nameGujarati: "બીસ્કીટ પરાઠા",
      },
      { id: "bajri-rotlo", name: "Bajri Rotlo", nameGujarati: "બાજરા રોટલો" },
      {
        id: "juvar-bajri-rotlo",
        name: "Juvar Bajri Rotlo",
        nameGujarati: "જુવાર બાજરા રોટલો",
      },
    ],
  },
  {
    id: "farshan",
    name: "Farshan",
    nameGujarati: "ફરસાણ",
    items: [
      {
        id: "corn-veg-handvo",
        name: "Corn Veg Handvo (Steam)",
        nameGujarati: "કોર્ન વેજ. હાંડવો",
      },
      {
        id: "veg-handvo-makens",
        name: "Veg. Handvo (Makens Red / Green) (Steam)",
        nameGujarati: "વેજ. હાંડવો (મખીન્સ રેડ / ગ્રીન)",
      },
      {
        id: "schezwan-handvo",
        name: "Schezwan Handvo (Steam)",
        nameGujarati: "સેઝવાન હાંડવો",
      },
      {
        id: "palak-handvo",
        name: "Palak Handvo (Steam)",
        nameGujarati: "પાલક હાંડવો",
      },
      {
        id: "spanish-handvo",
        name: "Spanish Handvo (Steam)",
        nameGujarati: "સ્પેનીસ હાંડવો",
      },
      { id: "steam-dhokla", name: "Steam Dhokla", nameGujarati: "સ્ટીમ ઢોકળા" },
      {
        id: "mix-dhokla",
        name: "Mix Dhokla (Palak Methi / Methi Chola / Pizza / Regular)",
        nameGujarati: "મીક્સ ઢોકળા (પાલક મેથી / મેથી છોલા / પીઝા / રેગ્યુલર)",
      },
      { id: "nylon-khaman", name: "Nylon Khaman", nameGujarati: "નાયલોન ખમણ" },
      {
        id: "patra",
        name: "Patra (Vagharela / Ras)",
        nameGujarati: "પાત્રા (વઘારેલા / રસ)",
      },
      { id: "khandvi", name: "Khandvi", nameGujarati: "ખાંડવી" },
      { id: "sev-khamani", name: "Sev Khamani", nameGujarati: "સેવ ખમણી" },
      {
        id: "white-chilli-milli",
        name: "White Chilli Milli",
        nameGujarati: "વ્હાઇટ ચીલી મીલી",
      },
      { id: "pudla", name: "Pudla", nameGujarati: "પુડલા" },
      {
        id: "vibrnat-gujarat",
        name: "Vibrnat Gujarat (Variety-4)",
        nameGujarati: "વાઇબ્રન્ટ ગુજરાત (વેરાયટી-૪)",
      },
      {
        id: "mix-bhajiya",
        name: "Mix Bhajiya (Fry)",
        nameGujarati: "મીક્સ ભજીયા",
      },
      { id: "cutlet", name: "Cutlet (Fry)", nameGujarati: "કટલેસ" },
      {
        id: "kothmir-kali",
        name: "Kothmir Kali (Fry)",
        nameGujarati: "કોથમીર કલી",
      },
      { id: "dal-vada", name: "Dal Vada (Fry)", nameGujarati: "દાલ વડા" },
      { id: "samosa", name: "Samosa (Fry)", nameGujarati: "સમોસા" },
      { id: "kachori", name: "Kachori (Fry)", nameGujarati: "કચોરી" },
      { id: "sev-roll", name: "Sev Roll (Fry)", nameGujarati: "સેવ રોલ" },
    ],
  },
  {
    id: "dal-rice",
    name: "Dal & Rice",
    nameGujarati: "દાળ અને રાઈસ",
    items: [
      { id: "gujarati-dal", name: "Gujarati Dal", nameGujarati: "ગુજરાતી દાળ" },
      { id: "kadhi", name: "Kadhi", nameGujarati: "કઢી" },
      {
        id: "rajasthani-kadhi",
        name: "Rajasthani Kadhi",
        nameGujarati: "રાજસ્થાની કઢી",
      },
      {
        id: "sp-urad-dal",
        name: "Sp. Urad Dal",
        nameGujarati: "સ્પે. અડદ દાળ",
      },
      { id: "dal-fry", name: "Dal Fry", nameGujarati: "દાલ ફ્રાય" },
      { id: "dal-tadka", name: "Dal Tadka", nameGujarati: "દાલ તડકા" },
      { id: "dal-makhani", name: "Dal Makhani", nameGujarati: "દાળ મખની" },
      { id: "plain-rice", name: "Plain Rice", nameGujarati: "પ્લેઇન રાઇસ" },
      {
        id: "dry-fruit-pulav",
        name: "Dry Fruit Pulav",
        nameGujarati: "ડ્રાયફ્રુટ પુલાવ",
      },
      { id: "veg-pulav", name: "Veg. Pulav", nameGujarati: "વેજ. પુલાવ" },
      {
        id: "pulav-taj-laving",
        name: "Pulav (Taj / Laving)",
        nameGujarati: "પુલાવ (તજ / લવીંગ)",
      },
      {
        id: "kashmiri-pulav",
        name: "Kashmiri Pulav",
        nameGujarati: "કાશ્મીરી પુલાવ",
      },
      { id: "jeera-rice", name: "Jeera Rice", nameGujarati: "જીરા રાઈસ" },
      { id: "veg-biryani", name: "Veg. Biryani", nameGujarati: "વેજ. બીરયાની" },
      {
        id: "handi-biryani",
        name: "Handi Biryani",
        nameGujarati: "હાંડી બીરયાની",
      },
      {
        id: "veg-fried-rice",
        name: "Veg. Fried Rice",
        nameGujarati: "વેજ. ફ્રાઈડ રાઈસ",
      },
      {
        id: "schezwan-fry-rice",
        name: "Schezwan Fry Rice",
        nameGujarati: "સેઝવાન ફ્રાય રાઇસ",
      },
      {
        id: "manchurian-rice",
        name: "Manchurian Rice",
        nameGujarati: "મંચુરીયન રાઇસ",
      },
      { id: "khichdi", name: "Khichdi", nameGujarati: "ખીચડી" },
      {
        id: "masala-khichdi",
        name: "Masala Khichdi",
        nameGujarati: "મસાલા ખીચડી",
      },
    ],
  },
  {
    id: "special-counters",
    name: "Special Counters",
    nameGujarati: "સ્પેશિયલ કાઉન્ટર્સ",
    items: [
      { id: "mocktail-counter", name: "Mocktail", nameGujarati: "મોકટેલ" },
      { id: "ice-cream-counter", name: "Ice Cream", nameGujarati: "આઈસક્રિમ" },
      {
        id: "shayari-pan-counter",
        name: "Shayari Pan",
        nameGujarati: "શાયરી પાન",
      },
      {
        id: "fruit-dish-counter",
        name: "Fruit Dish",
        nameGujarati: "ફ્રુટ ડીશ",
      },
      { id: "pop-corn-counter", name: "Pop Corn", nameGujarati: "પોપ કોર્ન" },
      {
        id: "american-corn-counter",
        name: "American Corn",
        nameGujarati: "અમેરીકન કોર્ન",
      },
      { id: "gola-counter", name: "Gola", nameGujarati: "ગોલા" },
      {
        id: "cold-drinks-counter",
        name: "Cold Drinks",
        nameGujarati: "કોલ્ડ્રીંક્સ",
      },
      {
        id: "coffee-bar-counter",
        name: "Coffee Bar",
        nameGujarati: "કોફી બાર",
      },
      { id: "brownie-counter", name: "Brownie", nameGujarati: "બ્રાઉની" },
    ],
  },
];

module.exports = { menuData };